### ISSUE TITLE
[FEAT]: Allow request customization

### ISSUE THREAD

**Issue by VanishMax** [codeacme17/1llest-waveform-vue#4]
### Description

Hi! I loved reading and using this library, it is simple yet powerful.

There was an issue for me while making requests. It is common to provide additional headers like `mode` or `authorization`, or even change methods for some cases. Therefore, I'd want to propose extending the request logic by adding the `requestOptions: RequestInit` property and pass it to `fetch` like this: `const response = await fetch(this.props.url, this.props.requestOptions);`

**Comment by codeacme17** [comment]
Thanks for your issue and the like! 
I apologize that I didn't take fetch's configurability into account during the initial design, I'll be adding that feature as soon as I can this week!

**Comment by VanishMax** [comment]
@codeacme17 I could implement it in the next hour if you're alright with that.

**Comment by codeacme17** [comment]
> @codeacme17 I could implement it in the next hour if you're alright with that.

Sure! I would greatly appreciate it if you could submit a PR!
